version: '3'
services:

  video_record:
    container_name: video_record
    image: techye/video_record
    restart: on-failure
    environment:
      - "ROS_MASTER_URI=http://ros_core:11311"
      - "TO_ROSBAG=FALSE"
    depends_on:
      - ros_core
    devices:
      - /dev/video0:/dev/video0

  ros_core:
    container_name: ros_core
    image: ros:kinetic-ros-core
    entrypoint: bash -c "source /opt/ros/kinetic/setup.bash; roscore;"
    restart: on-failure
