version: '3'
services:

  view_rosbag:
    container_name: view_rosbag
    image: view_rosbag
    restart: on-failure
    environment:
      - "ROS_MASTER_URI=http://ros_core:11311"
    depends_on:
      - ros_core
    devices:
      - /dev/video10:/dev/video0

  ros_core:
    container_name: ros_core
    image: ros:kinetic-ros-core
    entrypoint: bash -c "source /opt/ros/kinetic/setup.bash; roscore;"
    restart: on-failure
